<?php

namespace Database\Seeders;

use App\Models\Lead;
use App\Models\User;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class LeadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = User::first(); // Assign to first user

        $leads = [
            [
                'company_name' => 'Ristorante Il Gabbiano',
                'maps_link' => 'https://maps.google.com/?q=Ristorante+Il+Gabbiano+Rome',
                'website_url' => 'https://ilgabbiano-roma.it',
                'category' => 'restaurant',
                'description' => 'Restaurant italien élégant avec vue sur la mer, spécialisé dans les fruits de mer frais et les pâtes faites maison.',
                'contact_person' => 'Marco Bianchi',
                'contact_email' => 'marco@ilgabbiano.it',
                'contact_phone' => '+39 06 1234 5678',
                'status' => Lead::STATUS_CONTRACT_SIGNED,
                'priority' => Lead::PRIORITY_HIGH,
                'estimated_value' => 3500.00,
                'notes' => 'Client très intéressé. Préfère un design élégant avec beaucoup de photos. Budget confirmé.',
                'last_contact_date' => Carbon::now()->subDays(3),
                'next_follow_up_date' => Carbon::now()->addDays(5),
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Caffè Centrale Milano',
                'maps_link' => 'https://maps.google.com/?q=Caffe+Centrale+Milano',
                'website_url' => null,
                'category' => 'cafe',
                'description' => 'Café historique au cœur de Milan, connu pour son espresso exceptionnel et son atmosphère authentique.',
                'contact_person' => 'Giuseppe Verdi',
                'contact_email' => 'info@caffecentrale.it',
                'contact_phone' => '+39 02 9876 5432',
                'status' => Lead::STATUS_RDV_BOOKED,
                'priority' => Lead::PRIORITY_HIGH,
                'estimated_value' => 2800.00,
                'notes' => 'RDV prévu pour présentation. Veut un site avec réservation en ligne.',
                'last_contact_date' => Carbon::now()->subDays(7),
                'next_follow_up_date' => Carbon::now()->addDays(2),
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Hotel Bella Vista Firenze',
                'maps_link' => 'https://maps.google.com/?q=Hotel+Bella+Vista+Florence',
                'website_url' => 'https://bellavista-firenze.com',
                'category' => 'hotel',
                'description' => 'Hôtel-boutique 4 étoiles avec vue panoramique sur Florence. 25 chambres de luxe.',
                'contact_person' => 'Sofia Rossi',
                'contact_email' => 'sofia.rossi@bellavista.it',
                'contact_phone' => '+39 055 1234 9876',
                'status' => Lead::STATUS_RESPONSE_RECEIVED,
                'priority' => Lead::PRIORITY_MEDIUM,
                'estimated_value' => 4500.00,
                'notes' => 'Réponse positive reçue. Demande un devis détaillé avec système de réservation.',
                'last_contact_date' => Carbon::now()->subDays(10),
                'next_follow_up_date' => Carbon::now()->addDays(1),
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Trattoria da Nonna',
                'maps_link' => 'https://maps.google.com/?q=Trattoria+da+Nonna+Bologna',
                'website_url' => null,
                'category' => 'restaurant',
                'description' => 'Trattoria familiale traditionnelle servant la cuisine bolognaise authentique depuis 1952.',
                'contact_person' => 'Antonio Romano',
                'contact_email' => 'nonna@trattoria.it',
                'contact_phone' => '+39 051 7654 3210',
                'status' => Lead::STATUS_EMAIL_SENT,
                'priority' => Lead::PRIORITY_MEDIUM,
                'estimated_value' => 2200.00,
                'notes' => 'Premier email envoyé avec portfolio. En attente de réponse.',
                'last_contact_date' => Carbon::now()->subDays(5),
                'next_follow_up_date' => Carbon::now()->addDays(3),
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Bar Sportivo Torino',
                'maps_link' => 'https://maps.google.com/?q=Bar+Sportivo+Turin',
                'website_url' => null,
                'category' => 'bar',
                'description' => 'Bar sportif moderne avec écrans géants, populaire pour les matchs de foot.',
                'contact_person' => 'Luca Ferrari',
                'contact_email' => 'luca@barsportivo.it',
                'contact_phone' => null,
                'status' => Lead::STATUS_ANALYZED,
                'priority' => Lead::PRIORITY_LOW,
                'estimated_value' => 1800.00,
                'notes' => 'Prospect intéressant mais budget limité. À contacter après analyse complète.',
                'last_contact_date' => Carbon::now()->subDays(15),
                'next_follow_up_date' => Carbon::now()->addDays(7),
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Gelateria Artigianale Venezia',
                'maps_link' => 'https://maps.google.com/?q=Gelateria+Artigianale+Venice',
                'website_url' => null,
                'category' => 'cafe',
                'description' => 'Glacier artisanal réputé, glaces faites maison avec ingrédients bio et locaux.',
                'contact_person' => 'Elena Conti',
                'contact_email' => 'elena@gelateriaartigi.it',
                'contact_phone' => '+39 041 8765 4321',
                'status' => Lead::STATUS_NOT_TOUCHED,
                'priority' => Lead::PRIORITY_LOW,
                'estimated_value' => 1500.00,
                'notes' => 'Trouvé sur Google Maps. Pas encore contacté.',
                'last_contact_date' => null,
                'next_follow_up_date' => Carbon::now()->addDays(14),
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Osteria del Porto Napoli',
                'maps_link' => 'https://maps.google.com/?q=Osteria+del+Porto+Naples',
                'website_url' => 'https://osteriaporto.it',
                'category' => 'restaurant',
                'description' => 'Restaurant de poisson sur le port avec terrasse vue mer. Spécialités napolitaines.',
                'contact_person' => 'Vincenzo Marino',
                'contact_email' => 'info@osteriaporto.it',
                'contact_phone' => '+39 081 9876 5432',
                'status' => Lead::STATUS_WEBSITE_DELIVERED,
                'priority' => Lead::PRIORITY_HIGH,
                'estimated_value' => 3200.00,
                'notes' => 'Projet terminé et livré. Client très satisfait. Possibilité de refonte future.',
                'last_contact_date' => Carbon::now()->subDays(2),
                'next_follow_up_date' => null,
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Hotel Panorama Amalfi',
                'maps_link' => 'https://maps.google.com/?q=Hotel+Panorama+Amalfi+Coast',
                'website_url' => null,
                'category' => 'hotel',
                'description' => 'Hôtel 5 étoiles sur la côte amalfitaine avec piscine à débordement et spa.',
                'contact_person' => 'Carla Esposito',
                'contact_email' => 'carla@panorama-amalfi.it',
                'contact_phone' => '+39 089 1234 5678',
                'status' => Lead::STATUS_RDV_BOOKED,
                'priority' => Lead::PRIORITY_HIGH,
                'estimated_value' => 5500.00,
                'notes' => 'RDV téléphonique demain à 15h. Projet important avec système de réservation complexe.',
                'last_contact_date' => Carbon::now()->subDays(4),
                'next_follow_up_date' => Carbon::now()->addDay(),
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Pizzeria Margherita Classica',
                'maps_link' => 'https://maps.google.com/?q=Pizzeria+Margherita+Rome',
                'website_url' => null,
                'category' => 'restaurant',
                'description' => 'Pizzeria traditionnelle avec four à bois. Pizza napolitaine authentique.',
                'contact_person' => 'Tommaso Bruno',
                'contact_email' => 'tommaso@margheritaclassica.it',
                'contact_phone' => '+39 06 5555 4444',
                'status' => Lead::STATUS_NOT_TOUCHED,
                'priority' => Lead::PRIORITY_MEDIUM,
                'estimated_value' => 1900.00,
                'notes' => 'Recommandé par un client existant. À contacter rapidement.',
                'last_contact_date' => null,
                'next_follow_up_date' => Carbon::now()->addDays(5),
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Wine Bar La Cantina',
                'maps_link' => 'https://maps.google.com/?q=Wine+Bar+La+Cantina+Verona',
                'website_url' => 'https://lacantina-verona.it',
                'category' => 'bar',
                'description' => 'Bar à vin élégant avec sélection de vins italiens premium et tapas gastronomiques.',
                'contact_person' => 'Francesca Moro',
                'contact_email' => 'francesca@lacantina.it',
                'contact_phone' => '+39 045 7777 8888',
                'status' => Lead::STATUS_ANALYZED,
                'priority' => Lead::PRIORITY_MEDIUM,
                'estimated_value' => 2400.00,
                'notes' => 'Analyse terminée. Site actuel obsolète. Demande un design moderne et épuré.',
                'last_contact_date' => Carbon::now()->subDays(12),
                'next_follow_up_date' => Carbon::now()->addDays(4),
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Bistrot Parisien Milano',
                'maps_link' => 'https://maps.google.com/?q=Bistrot+Parisien+Milan',
                'website_url' => null,
                'category' => 'cafe',
                'description' => 'Café-bistrot français au cœur de Milan. Croissants, quiches et ambiance parisienne.',
                'contact_person' => 'Pierre Dubois',
                'contact_email' => 'pierre@bistrotparisien.it',
                'contact_phone' => '+39 02 3333 2222',
                'status' => Lead::STATUS_EMAIL_SENT,
                'priority' => Lead::PRIORITY_LOW,
                'estimated_value' => 1600.00,
                'notes' => 'Email envoyé il y a une semaine. Pas de réponse encore.',
                'last_contact_date' => Carbon::now()->subDays(7),
                'next_follow_up_date' => Carbon::now()->addDays(2),
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Ristorante Stella Marina',
                'maps_link' => 'https://maps.google.com/?q=Ristorante+Stella+Marina+Genoa',
                'website_url' => null,
                'category' => 'restaurant',
                'description' => 'Restaurant fruits de mer étoilé Michelin. Cuisine raffinée avec produits locaux.',
                'contact_person' => 'Roberto Genovese',
                'contact_email' => 'roberto@stellamarina.it',
                'contact_phone' => '+39 010 9999 1111',
                'status' => Lead::STATUS_RESPONSE_RECEIVED,
                'priority' => Lead::PRIORITY_HIGH,
                'estimated_value' => 4800.00,
                'notes' => 'Très intéressé. Veut un site haut de gamme avec galerie photos professionnelle.',
                'last_contact_date' => Carbon::now()->subDays(6),
                'next_follow_up_date' => Carbon::now()->subDay(), // Overdue
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Hotel Boutique Toscana',
                'maps_link' => 'https://maps.google.com/?q=Hotel+Boutique+Tuscany',
                'website_url' => 'https://boutique-toscana.it',
                'category' => 'hotel',
                'description' => 'Petit hôtel de charme dans les collines toscanes. 12 chambres avec piscine.',
                'contact_person' => 'Isabella Montanari',
                'contact_email' => 'isabella@boutique-toscana.it',
                'contact_phone' => '+39 0577 4444 5555',
                'status' => Lead::STATUS_CONTRACT_SIGNED,
                'priority' => Lead::PRIORITY_HIGH,
                'estimated_value' => 3800.00,
                'notes' => 'Contrat signé. Début du projet la semaine prochaine.',
                'last_contact_date' => Carbon::now()->subDay(),
                'next_follow_up_date' => Carbon::now()->addDays(7),
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Caffè Letterario Roma',
                'maps_link' => 'https://maps.google.com/?q=Caffe+Letterario+Rome',
                'website_url' => null,
                'category' => 'cafe',
                'description' => 'Café-librairie culturel avec événements littéraires et concerts acoustiques.',
                'contact_person' => 'Giulia Ferretti',
                'contact_email' => 'giulia@caffeletterario.it',
                'contact_phone' => null,
                'status' => Lead::STATUS_NOT_TOUCHED,
                'priority' => Lead::PRIORITY_LOW,
                'estimated_value' => 1400.00,
                'notes' => 'Contact obtenu lors d\'un événement networking. À qualifier.',
                'last_contact_date' => null,
                'next_follow_up_date' => Carbon::now()->addDays(10),
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Enoteca Il Vigneto',
                'maps_link' => 'https://maps.google.com/?q=Enoteca+Il+Vigneto+Siena',
                'website_url' => null,
                'category' => 'bar',
                'description' => 'Cave à vin et dégustation. Plus de 500 références de vins italiens.',
                'contact_person' => 'Matteo Sangiovese',
                'contact_email' => 'matteo@ilvigneto.it',
                'contact_phone' => '+39 0577 6666 7777',
                'status' => Lead::STATUS_ANALYZED,
                'priority' => Lead::PRIORITY_MEDIUM,
                'estimated_value' => 2100.00,
                'notes' => 'Analyse complète. Concurrent direct a un bon site. Opportunité intéressante.',
                'last_contact_date' => Carbon::now()->subDays(8),
                'next_follow_up_date' => Carbon::now()->addDays(6),
                'assigned_to' => $user?->id,
            ],
            [
                'company_name' => 'Ristorante Vista Lago Como',
                'maps_link' => 'https://maps.google.com/?q=Ristorante+Vista+Lago+Como',
                'website_url' => 'https://vistalago-como.it',
                'category' => 'restaurant',
                'description' => 'Restaurant gastronomique avec terrasse panoramique sur le lac de Côme.',
                'contact_person' => 'Alessandro Lombardi',
                'contact_email' => 'info@vistalago.it',
                'contact_phone' => '+39 031 8888 9999',
                'status' => Lead::STATUS_EMAIL_SENT,
                'priority' => Lead::PRIORITY_HIGH,
                'estimated_value' => 3900.00,
                'notes' => 'Email de présentation envoyé. Site actuel très basique. Grand potentiel.',
                'last_contact_date' => Carbon::now()->subDays(4),
                'next_follow_up_date' => Carbon::now()->addDays(3),
                'assigned_to' => $user?->id,
            ],
        ];

        foreach ($leads as $leadData) {
            Lead::create($leadData);
        }
    }
}
